### ISSUE TITLE
Add a bit more flexibility to displaying a response

### ISSUE THREAD

**Issue by moonglum** [innoq/tabelle#4]
When a user does a search that comes back with no results, I want to show a helpful hint like "Your search did not return any results." I want to be able to translate this and I want to be able to style it, so I would like to generate that answer on the server side. However, I can currently only return a tbody, so I don't have that option. Suggestion:

The user needs to provide an `id` on the `ta-belle` element. If they don't, they will receive an error (I think I would just do a `console.error("...")` and then not activate ta-belle). When ta-belle receives the answer from the server, it will search for the element with the same ID and replace its content with the content of that element. Afterwards, it will re-add the filters. This allows users to add additional elements to the response other than the table.

What do you think? Thanks for the project, it really helps me get things done <3

**Comment by joyheron** [comment]
Thank you for the suggestion! This behavior has been implemented and released in version 0.0.13!

**Comment by moonglum** [comment]
This works as expected 👍 Thank you so much!
